name: Build/Test on Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      Solution_Name: 'Freedom35.ImageProcessing.sln'

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore $Solution_Name
    - name: Build
      run: dotnet build $Solution_Name --no-restore --configuration Release
    - name: Test
      run: dotnet test $Solution_Name --no-build --verbosity normal --configuration Release
