name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      Solution_Name: Freedom35.ImageProcessing.sln

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore ${{ Solution_Name }}
    - name: Build
      run: dotnet build ${{ Solution_Name }} --no-restore
    - name: Test
      run: dotnet test ${{ Solution_Name }} --no-build --verbosity normal
