# Workflow to build/test image processing lib
name: Build/Test on Windows Desktop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  solution: 'Freedom35.ImageProcessing.sln'
  build_config: 'Release'

jobs:

  build-and-test:

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ env.solution }}

    - name: Build
      run: dotnet build ${{ env.solution }} --configuration ${{ env.build_config }} --no-restore

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test ${{ env.solution }} --configuration ${{ env.build_config }} --no-build
